// Enterprise role-based access
export const FLEET_MANAGER = 'FLEET_MANAGER';
export const DISPATCHER = 'DISPATCHER';
export const SAFETY_OFFICER = 'SAFETY_OFFICER';
export const FINANCIAL_ANALYST = 'FINANCIAL_ANALYST';
export const DRIVER = 'DRIVER';

// Manager: full access
export const CAN_MANAGE_VEHICLES = [FLEET_MANAGER];
export const CAN_MANAGE_DRIVERS = [FLEET_MANAGER];
export const CAN_DISPATCH_TRIPS = [FLEET_MANAGER, DISPATCHER];
export const CAN_MANAGE_MAINTENANCE = [FLEET_MANAGER];
export const CAN_MANAGE_FUEL = [FLEET_MANAGER, FINANCIAL_ANALYST];
export const CAN_VIEW_ANALYTICS = [FLEET_MANAGER, FINANCIAL_ANALYST];
export const CAN_VIEW_FINANCE = [FLEET_MANAGER, FINANCIAL_ANALYST];
export const CAN_EDIT_REVENUE = [FLEET_MANAGER, FINANCIAL_ANALYST];
export const CAN_MANAGE_COMPANIES = [FLEET_MANAGER];

// Safety Officer: compliance, incidents, safety approval (not read-only)
export const CAN_MANAGE_COMPLIANCE = [FLEET_MANAGER, SAFETY_OFFICER];
export const CAN_MANAGE_INCIDENTS = [FLEET_MANAGER, SAFETY_OFFICER];
export const CAN_APPROVE_TRIP_SAFETY = [FLEET_MANAGER, SAFETY_OFFICER];
export const CAN_VIEW_SAFETY_DASHBOARD = [FLEET_MANAGER, SAFETY_OFFICER];

// Driver: own trips, update location, odometer
export const CAN_DRIVER_PANEL = [FLEET_MANAGER, DRIVER];

// Who can see vehicles/drivers (for dispatch)
export const CAN_VIEW_VEHICLES = [FLEET_MANAGER, DISPATCHER, SAFETY_OFFICER, FINANCIAL_ANALYST];
export const CAN_VIEW_DRIVERS = [FLEET_MANAGER, DISPATCHER, SAFETY_OFFICER, FINANCIAL_ANALYST];
